services:
  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"
    environment:
      USER_SERVICE_PORT: "8001"

  order-service:
    build: ./services/order-service
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      ORDER_SERVICE_PORT: "8002"
      USER_SERVICE_URL: http://user-service:8001
      A_SERVICE_URL: http://a-service:8003
      REDIS_OM_URL: ${REDIS_OM_URL}
    depends_on:
      - user-service
      - a-service

  a-service:
    build: ./services/a
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      A_SERVICE_PORT: "8003"
      REDIS_OM_URL: ${REDIS_OM_URL}
