services:
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "50051:50051"
    environment:
      GRPC_PORT: "50051"

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      ORDER_SERVICE_PORT: "8002"
      USER_SERVICE_GRPC_TARGET: user-service:50051
      A_SERVICE_GRPC_TARGET: a-service:50053
      REDIS_OM_URL: ${REDIS_OM_URL}
    depends_on:
      - user-service
      - a-service

  a-service:
    build:
      context: .
      dockerfile: services/a/Dockerfile
    ports:
      - "8003:8003"
      - "50053:50053"
    env_file:
      - .env
    environment:
      A_SERVICE_PORT: "8003"
      GRPC_PORT: "50053"
      REDIS_OM_URL: ${REDIS_OM_URL}
